# POST http://localhost:8080/company
# Content-Type: application/json

# {
#   "email": "teste@gmail.com",
#   "password": "teste"
# }

GET http://localhost:8080/company/1/employees
Content-Type: application/json
